import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-gray-50 dark:bg-gray-900">
        <aside className="w-56 bg-white dark:bg-gray-800 shadow-md flex flex-col p-4 min-h-screen">
          <h1 className="text-xl font-bold mb-8">Finance App</h1>
          <nav className="flex flex-col gap-4">
            <Link href="/" className="hover:text-blue-600 font-medium">Dashboard</Link>
            <Link href="/expenditure" className="hover:text-blue-600 font-medium">Expenditure</Link>
            <Link href="/income" className="hover:text-blue-600 font-medium">Income</Link>
            <Link href="/assets" className="hover:text-blue-600 font-medium">Assets</Link>
            <Link href="/liabilities" className="hover:text-blue-600 font-medium">Liabilities</Link>
          </nav>
        </aside>
        <main className="flex-1 p-8">{children}</main>
      </body>
    </html>
  );
}
